"""typo execution_avgPrice, add bridge symbology insert_datetime

Revision ID: c0a3010351ad
Revises: c9868eea18f3
Create Date: 2018-11-19 16:00:00.586013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0a3010351ad'
down_revision = 'c9868eea18f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibexecutionrestful', sa.Column('execution_m_avgPrice', sa.Numeric(precision=15, scale=6), nullable=True))
    op.drop_column('ibexecutionrestful', 'execution_avgPrice')
    op.add_column('ibsymbology', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('ibsymbology', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibsymbology', 'updated')
    op.drop_column('ibsymbology', 'created')
    op.add_column('ibexecutionrestful', sa.Column('execution_avgPrice', mysql.DECIMAL(precision=15, scale=6), nullable=True))
    op.drop_column('ibexecutionrestful', 'execution_m_avgPrice')
    # ### end Alembic commands ###
