"""execs pool

Revision ID: c9868eea18f3
Revises: 57dbc829856f
Create Date: 2018-10-23 17:31:05.549254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9868eea18f3'
down_revision = '57dbc829856f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibcontract',
    sa.Column('assetCategory', sa.String(length=25), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=75), nullable=True),
    sa.Column('conid', sa.BigInteger(), nullable=False),
    sa.Column('isin', sa.String(length=25), nullable=True),
    sa.Column('listingExchange', sa.String(length=25), nullable=True),
    sa.Column('underlyingConid', sa.Numeric(precision=15, asdecimal=False), nullable=True),
    sa.Column('underlyingSymbol', sa.String(length=50), nullable=True),
    sa.Column('underlyingSecurityID', sa.String(length=25), nullable=True),
    sa.Column('underlyingListingExchange', sa.String(length=25), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('strike', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('putCall', sa.String(length=10), nullable=True),
    sa.Column('maturity', sa.Date(), nullable=True),
    sa.Column('issueDate', sa.Date(), nullable=True),
    sa.Column('underlyingCategory', sa.String(length=25), nullable=True),
    sa.Column('subCategory', sa.String(length=25), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('conid')
    )
    op.create_table('ibexecutionrestful',
    sa.Column('execution_m_acctNumber', sa.String(length=25), nullable=True),
    sa.Column('execution_m_orderId', sa.BigInteger(), nullable=True),
    sa.Column('execution_m_time', sa.DateTime(), nullable=True),
    sa.Column('execution_m_permId', sa.BigInteger(), nullable=True),
    sa.Column('execution_m_price', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('execution_avgPrice', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('execution_m_cumQty', sa.BigInteger(), nullable=True),
    sa.Column('execution_m_side', sa.String(length=15), nullable=True),
    sa.Column('execution_m_clientId', sa.Integer(), nullable=True),
    sa.Column('execution_m_shares', sa.BigInteger(), nullable=True),
    sa.Column('execution_m_execId', sa.String(length=140), nullable=False),
    sa.Column('execution_m_exchange', sa.String(length=25), nullable=True),
    sa.Column('contract_m_tradingClass', sa.String(length=15), nullable=True),
    sa.Column('contract_m_symbol', sa.String(length=50), nullable=True),
    sa.Column('contract_m_conId', sa.BigInteger(), nullable=False),
    sa.Column('contract_m_secType', sa.String(length=25), nullable=True),
    sa.Column('contract_m_right', sa.String(length=25), nullable=True),
    sa.Column('contract_m_multiplier', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('contract_m_expiry', sa.Date(), nullable=True),
    sa.Column('contract_m_localSymbol', sa.String(length=75), nullable=False),
    sa.Column('contract_m_exchange', sa.String(length=25), nullable=True),
    sa.Column('contract_m_strike', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ibcontract_conid', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ibcontract_conid'], ['ibcontract.conid'], ),
    sa.PrimaryKeyConstraint('execution_m_execId')
    )
    op.create_table('ibsymbology',
    sa.Column('ticker', sa.String(length=75), nullable=True),
    sa.Column('bbgIdentifier', sa.String(length=50), nullable=True),
    sa.Column('bbgUnderylingId', sa.String(length=50), nullable=True),
    sa.Column('internalUnderlying', sa.String(length=50), nullable=True),
    sa.Column('ibcontract_conid', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ibcontract_conid'], ['ibcontract.conid'], ),
    sa.PrimaryKeyConstraint('ibcontract_conid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibsymbology')
    op.drop_table('ibexecutionrestful')
    op.drop_table('ibcontract')
    # ### end Alembic commands ###
