apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ib-backend
  namespace: ib
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: ib.stouffcapital.com
    
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120s"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ib.stouffcapital.com
    secretName: ib-stouffcapital-service-tls
  rules:
  - host: ib.stouffcapital.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ib-backend
            port: 
              number: 5000
