apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ib-backend
  namespace: ib
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120s"
spec:
  tls:
  - hosts:
    - ib.stouffcapital.com
    secretName: ib-stouffcapital-service-tls
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: ib.stouffcapital.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ib-backend
          servicePort: 5000
