apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ib-backend-pv-claim
  namespace: ib
  labels:
    app: ib
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
