apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ib
  name: ib-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]