apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ib
  name: ib-role_ib-sa
subjects:
- kind: ServiceAccount
  name: ib-sa
  namespace: ib
roleRef:
  kind: Role
  name: ib-role
  apiGroup: rbac.authorization.k8s.io