apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ib
  namespace: ib
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120s"
spec:
  tls:
  - hosts:
    - ib.stouffcapital.tech
    secretName: ib-stouffcapital-service-tls
  rules:
  - host: ib.stouffcapital.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ib-backend
            port: 
              number: 5000